### ISSUE TITLE
有考虑做成nonebot插件吗

### ISSUE THREAD

**Issue by yuanzhidao** [chingkingm/honkai_mys#16]
有考虑做成nonebot插件吗

**Comment by chingkingm** [comment]
目前没有计划，没写过nonebot的

**Comment by doiss** [comment]
使用bh#指令发出的图片是歪的
![Q@ZF_0$A@G7P46D3OHSGF6O](https://user-images.githubusercontent.com/97965580/153814000-650701d8-a7cd-4bb7-82f2-dc5a791b260a.PNG)

**Comment by chingkingm** [comment]
适配了nonebot2 2.0.0b1/b2
https://github.com/chingkingm/honkai_mys/tree/nonebot
