### ISSUE TITLE
关于bh#指令制作出的图片，文字位置偏移了

### ISSUE THREAD

**Issue by doiss** [chingkingm/honkai_mys#19]
@chingkingm 大佬这个怎么解决啊qaq
![Q@ZF_0$A@G7P46D3OHSGF6O](https://user-images.githubusercontent.com/97965580/153814433-e70a82dc-c4e5-4c8f-bd95-d77de9cd78a2.PNG)

**Comment by doiss** [comment]
除了添加ck我没有改任何代码

**Comment by chingkingm** [comment]
解决了？

**Comment by doiss** [comment]
没有
qaq

**Comment by doiss** [comment]
额，我好像是按错了

**Comment by doiss** [comment]
按成关闭问题按钮了qaq

**Comment by doiss** [comment]
@chingkingm 大佬帮帮我qaq

**Comment by chingkingm** [comment]
可能是你的pillow版本问题，看看这里升级一下 https://github.com/H-K-Y/Genshin_Impact_bot/issues/37#issuecomment-911233563

**Comment by doiss** [comment]
> 可能是你的pillow版本问题，看看这里升级一下 [H-K-Y/Genshin_Impact_bot#37 （comment）](https://github.com/H-K-Y/Genshin_Impact_bot/issues/37#issuecomment-911233563)

谢谢大佬，已经好了，是pillow版本低了，更新一下就好了
