### ISSUE TITLE
求解答bh#指令没反应报错

### ISSUE THREAD

**Issue by doiss** [chingkingm/honkai_mys#22]
![_2WV2YU~SDC5B{D1DK $DNE](https://user-images.githubusercontent.com/97965580/158379073-e831341f-62c1-4d92-ab3d-31ee82593803.png)

**Comment by doiss** [comment]
![image](https://user-images.githubusercontent.com/97965580/158385681-ce141ebb-45ed-423a-b14a-01f2ef26d16c.png)

**Comment by chingkingm** [comment]
看样子是米游社更新了新的量子流形，暂时还没适配，终极区的应该不受影响

**Comment by doiss** [comment]
哦扫噶
