### ISSUE TITLE
[报错]bh#绘图命令报错

### ISSUE THREAD

**Issue by RemKeeper** [chingkingm/honkai_mys#38]
![image](https://user-images.githubusercontent.com/78486275/163908336-68484d50-2456-4aea-95e1-00e0007821dc.png)
gocq那边说账号被风控，可是只有这个插件无法发送图片

**Comment by chingkingm** [comment]
这看起来时回复消息风控发不出去，还没到发图的环节。

风控没法解决，可以试试不发回复消息，即注释掉`reply`有关的行

**Comment by RemKeeper** [comment]
> 这看起来时回复消息风控发不出去，还没到发图的环节。
> 
> 风控没法解决，可以试试不发回复消息，即注释掉`reply`有关的行

OK,解决力，感谢大佬
