### ISSUE TITLE
nonebot2版本直接发bhf会报错，而bhf绑定<XXX>不会报错，怎么解决

### ISSUE THREAD

**Issue by liuzj288** [chingkingm/honkai_mys#42]

**Comment by liuzj288** [comment]
![image](https://user-images.githubusercontent.com/13833404/177072084-0b66c111-b745-4445-b059-e1a71b10828f.png)

**Comment by chingkingm** [comment]
这是go那边有问题啊，是不是被风控了

**Comment by liuzj288** [comment]
> 
但是其他指令都没问题可以正常发送，就这个bhf有这个问题，是不是判断逻辑有点问题
![image](https://user-images.githubusercontent.com/13833404/177183356-4381154b-cd27-4ec5-8f1d-cb63d621cb5f.png)
![image](https://user-images.githubusercontent.com/13833404/177183517-67f570be-e352-48e6-b0dd-bf41147e8def.png)

**Comment by chingkingm** [comment]
风控就是这么玄学的东西，一般图片不会风控，如果一直不好的话，可以借助问答插件，把回复的消息截图放到答里

**Comment by doiss** [comment]
> > 
> 
> 但是其他指令都没问题可以正常发送，就这个bhf有这个问题，是不是判断逻辑有点问题 ![图像](https://user-images.githubusercontent.com/13833404/177183356-4381154b-cd27-4ec5-8f1d-cb63d621cb5f.png) ![图像](https://user-images.githubusercontent.com/13833404/177183517-67f570be-e352-48e6-b0dd-bf41147e8def.png)

![image](https://user-images.githubusercontent.com/97965580/205449127-1f5b16ee-dc0e-4867-bc91-d0b14a8f6dcd.png)
这样改一下试试，我这样可以正常发出
