### ISSUE TITLE
请问绑定用的cookie的格式是？

### ISSUE THREAD

**Issue by Kiana1314** [chingkingm/honkai_mys#43]
bhf绑定0000000,xxxxxxxxxxxx发给机器人一直提示登录失效，请重新登录
用的这个在无痕模式获取的
javascript:(()=>{_=(n)=>{for(i in(r=document.cookie.split(";"))){var arr=r[i].split("=");if(arr[0].trim()==n)return arr[1];}};c=_("cookie_token")||alert('请重新登录');m=_("account_id")+","+c;c&&confirm('确定复制到剪切板?:'+m)&&copy(m)})();

**Comment by chingkingm** [comment]
![IMG_20220704_134633.jpg](https://user-images.githubusercontent.com/17588900/177089152-e980a53d-9521-4841-9a9f-4fba725dfdaf.jpg)

中间不要有空格或者回车

**Comment by Kiana1314** [comment]
![XN8CYUV`V) 3$BKLP_HP}TS](https://user-images.githubusercontent.com/107671434/177096211-883e7349-e9e8-4e74-ade1-c04f93714cfe.png)

**Comment by chingkingm** [comment]
..这是什么高级错误。。pillow版本是多少

**Comment by Kiana1314** [comment]
9.2.0

**Comment by chingkingm** [comment]
按理说这个地方不应该会出错。你可以加一下hoshino的[群](https://jq.qq.com/?_wv=1027&k=wgirhYYQ)，然后群里找我

**Comment by chingkingm** [comment]
Pillow9.2.0有问题，需要降级 pip install Pillow<9.2.0
