### ISSUE TITLE
9061.png头像素材出错，文件不对啦

### ISSUE THREAD

**Issue by liuzj288** [chingkingm/honkai_mys#44]
![image](https://user-images.githubusercontent.com/13833404/178053102-70a9b2a5-491d-4ff5-8bc5-6423d323ce05.png)
不如给个资源仓库位置

**Comment by chingkingm** [comment]
我也没有资源仓库哇，这都是从miHoYo那边爬的，很多都是给了URL但是没有实际资源。可以把404那张图复制一份改为9061
