### ISSUE TITLE
除签到外的指令没有反应

### ISSUE THREAD

**Issue by A7424** [chingkingm/honkai_mys#45]
显示登陆失效，请重新登录，更换cookie后重启hoshino问题依旧存在，但签到还能用，之后尝试重新clone，指令有反应但不输出图片，“#”在前是因为我改过指令
![FOBCA5KGX5NJSPGSGG@ XY](https://user-images.githubusercontent.com/103619507/181879792-dbcd7832-d110-41df-b95f-5a69809bad25.png)
![ZO%JRU@1T~C`28Z9Q87WP44](https://user-images.githubusercontent.com/103619507/181879797-8505e383-9e54-4a82-9bd4-d9447709a26e.png)
![S7`C2 X1_APFC 995JZ6_{F](https://user-images.githubusercontent.com/103619507/181879801-1c926a84-951e-4c70-86cf-6ed43ae779c3.png)
后台并没有任何消息
![J}I_%RBJ( 6USC1G@UHCOQW](https://user-images.githubusercontent.com/103619507/181879769-d4d71d54-9429-4d6d-90e1-00ec84d1e988.png)

**Comment by A7424** [comment]
有一张图片被吞了
![ZO%JRU@1T~C`28Z9Q87WP44](https://user-images.githubusercontent.com/103619507/181879894-37f6ab73-8190-4849-9866-0590cbcb244b.png)

**Comment by chingkingm** [comment]
config里的cookie是怎么填的呢

**Comment by A7424** [comment]
> config里的cookie是怎么填的呢

不好意思，没看见消息，按理来说应该是没有问题的，之前我也是这样填的
![)NA1ASLLKU_1RE{ 1 Y{R9V](https://user-images.githubusercontent.com/103619507/182564936-730bfd01-e183-437c-abf8-9a56fc62e97e.png)

**Comment by A7424** [comment]
> config里的cookie是怎么填的呢

现在好像因为崩坏三社区签到的接口换了，签到也没有反应了

**Comment by chingkingm** [comment]
签到的话已经更新了，pull最新版即可
其他指令没反应需要看hoshino那边的日志

**Comment by A7424** [comment]
> 签到的话已经更新了，pull最新版即可 其他指令没反应需要看hoshino那边的日志
更新到最新版本依旧没有反应，查询卡片显示登录失败，自动签到回复自动签到失败，尝试过无痕以及退出登录再获取cookie
![RTPN0`D8Z3 P}8KLE860GA1](https://user-images.githubusercontent.com/103619507/182568790-110134c6-bf0f-4193-afd3-0be6432b39ae.png)
![Z`97_0~EF{@7F7 XXA5UNT](https://user-images.githubusercontent.com/103619507/182569735-b54a504a-60e7-492e-ba16-a534be801597.png)

**Comment by A7424** [comment]
> 签到的话已经更新了，pull最新版即可 其他指令没反应需要看hoshino那边的日志

一张图片被吞了
![RTPN0`D8Z3 P}8KLE860GA1](https://user-images.githubusercontent.com/103619507/182569889-b98be61d-075a-4770-8c9a-ca748380a55d.png)

**Comment by chingkingm** [comment]
加我QQ吧

**Comment by A7424** [comment]
申请了
