### ISSUE TITLE
关于nonebot无法加载签到和猜语音模块

### ISSUE THREAD

**Issue by doiss** [chingkingm/honkai_mys#52]
我在安装目录中看到这一句话：《修改相应文件以加载插件》

**Comment by doiss** [comment]
请问佬有教程吗？实在是不会改啊 @chingkingm

**Comment by chingkingm** [comment]
参考https://v2.nonebot.dev/docs/tutorial/plugin/load-plugin

**Comment by doiss** [comment]
![QQ图片20221203221804](https://user-images.githubusercontent.com/97965580/205445396-14ab48cf-337d-40aa-8c52-1f7410fa0ca6.png)
感谢大佬，通过更改pyproject.toml成功加载，目前没发现问题
