### ISSUE TITLE
运行报错，求教

### ISSUE THREAD

**Issue by FairyReimu** [chingkingm/honkai_mys#7]
查询首选说找不到data目录，然后创建了data目录后，类报错信息如下：
honkai_mys/mypillow.py", line 36, in radar
    origin_image = self._image
AttributeError: 'myDraw' object has no attribute '_image'

**Comment by chingkingm** [comment]
请提供一下你的pillow版本

**Comment by FairyReimu** [comment]
> 请提供一下你的pillow版本

7.2.0

**Comment by chingkingm** [comment]
> > 请提供一下你的pillow版本
> 
> 7.2.0

看了下源码，这个属性之前是用`self.im`表示的，先替换试试。
我之后改一版不用`self._image`的

**Comment by FairyReimu** [comment]
> > > 请提供一下你的pillow版本
> > 
> > 
> > 7.2.0
> 
> 看了下源码，这个属性之前是用`self.im`表示的，先替换试试。 我之后改一版不用`self._image`的

有此想法改过一次，然后是另一个报错就又改回来了
mypillow.py", line 57, in radar
    @staticmethod
AttributeError: 'ImagingCore' object has no attribute 'alpha_composite'

**Comment by chingkingm** [comment]
发到新分支里了，麻烦测试一下
（更新pillow应该也行

**Comment by FairyReimu** [comment]
> 



> 发到新分支里了，麻烦测试一下 （更新pillow应该也行

可以了，正常运行，感谢！
大佬加油，争取把卡片视觉效果完善~

**Comment by chingkingm** [comment]
#8
