### ISSUE TITLE
大佬，指令error，求助

### ISSUE THREAD

**Issue by Juenia** [chingkingm/honkai_mys#9]
Cookies格式我按照egenshin的填入了，输入指令后，控制台弹出以下error
![Screenshot_20220121_113725_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/150461509-f74d1a88-f871-4212-83f4-511c2feec347.jpg)
求助。

**Comment by chingkingm** [comment]
egenshin格式如果是指yss获取的`10000000,E9xxxxxxxxxxK`这样的，填在config里是不能用的
需要的格式是
> `accoun_id=1000000;cookie_token=E9xxxxxxxxxxK`

**Comment by Juenia** [comment]
> egenshin格式如果是指yss获取的`10000000,E9xxxxxxxxxxK`这样的，填在config里是不能用的 需要的格式是
> 
> > `accoun_id=1000000;cookie_token=E9xxxxxxxxxxK`

就是这样的
![Screenshot_20220121_122512](https://user-images.githubusercontent.com/48351858/150465558-841cd29f-a96a-4531-8ae8-3d8e6d378376.jpg)

**Comment by chingkingm** [comment]
取消187行` # print(data)`的注释看看输出吧

**Comment by Juenia** [comment]
> 取消187行` # print(data)`的注释看看输出吧

大佬，，，打扰了，，我的问题。
我太蠢了。。。
cookies失效了才发现。。。【欲哭无泪】
很抱歉！！

**Comment by Juenia** [comment]
![Screenshot_20220121_125007](https://user-images.githubusercontent.com/48351858/150467774-fc03540e-2fc9-4afc-9303-707dd9271c09.jpg)
cookies刚更新后，现在输出变成了这个

**Comment by chingkingm** [comment]
。。这个号没打过深渊战场是吧，我还真没考虑到这种情况

**Comment by Juenia** [comment]
> 。。这个号没打过深渊战场是吧，我还真没考虑到这种情况

这样啊，那我绑另一个号试试

**Comment by chingkingm** [comment]
是你查的这个号没打过，跟绑定的没关系

**Comment by Juenia** [comment]
> 是你查的这个号没打过，跟绑定的没关系

嗯，我明白，所以我绑了大号的角色进去了
